/**
 * Patient and Clinical Session Status Lifecycle Constants
 * Aligned with Documentation/database.md and Documentation/PRD.md
 */
export const SESSION_STATUS = Object.freeze({
  STARTED: 'STARTED',
  IDENTIFIED: 'IDENTIFIED',
  CONSENT_PENDING: 'CONSENT_PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  HISTORY_IN_PROGRESS: 'HISTORY_IN_PROGRESS',
  DOCUMENT_PROCESSING: 'DOCUMENT_PROCESSING',
  PRIORITY_TRIAGE: 'PRIORITY_TRIAGE',
  READY_FOR_DOCTOR: 'READY_FOR_DOCTOR',
  DOCTOR_REVIEW: 'DOCTOR_REVIEW',
  COMPLETED: 'COMPLETED',
  CONSULTATION_COMPLETE: 'CONSULTATION_COMPLETE',
});

export const CONSENT_STATUS = Object.freeze({
  GRANTED: 'GRANTED',
  REVOKED: 'REVOKED',
});

export const CONSENT_TYPE = Object.freeze({
  AI_CASE_TAKING: 'AI_CASE_TAKING',
  DOCUMENT_PROCESSING: 'DOCUMENT_PROCESSING',
  ABDM_DATA_SHARING: 'ABDM_DATA_SHARING',
});

export const RECORD_REVIEW_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

export const RED_FLAG_SEVERITY = Object.freeze({
  NONE: 'NONE',
  LOW: 'LOW',
  MODERATE: 'MODERATE',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

export const OBSERVATION_CATEGORY = Object.freeze({
  SYMPTOM: 'SYMPTOM',
  MEDICATION: 'MEDICATION',
  ALLERGY: 'ALLERGY',
  CONDITION: 'CONDITION',
  LAB_RESULT: 'LAB_RESULT',
});

export default {
  SESSION_STATUS,
  CONSENT_STATUS,
  CONSENT_TYPE,
  RECORD_REVIEW_STATUS,
  RED_FLAG_SEVERITY,
  OBSERVATION_CATEGORY,
};
